workspace/config/routes.rb
Rails.application.routes.draw do
  resources :destinations

  get 'index' => 'welcome#index'

  get 'about' => 'welcome#about'
  
  get 'contact' => 'welcome#contact'
  
  get 'destinations' => 'destinations#index'
  
  get 'destination' => 'destinations#index'
  
  
  root 'welcome#index'
  

end

workspace/app/models/destination.rb
class Destination < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "800x600>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end
    

workspace/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

workspace/app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
  def index
    # @destinations = Destination.all
    if params[:country]
      @destinations = Destination.where(country:  params[:country].upcase)
    else  
      @destinations = Destination.all
    end
    
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:city, :country, :description, :population, :avatar)
    end
end

workspace/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # def initialize
  #     @width= 4241/8
  #     @height = 3439/8
  # end 
  
  def index
      @homeland ='Puerto Rico'
      @countries = ['Chile', 'Brazil', 'Colombia','Peru']
      @united_states ={'capital_city'=>'washington,dc', 'favorite_city' => 'Fort Worth', 'favorite_state'=> 'Texas', 'flag-colors'=>'red white blue'}
      
      
  end

  def about
    @imagesarray = ['123.jpg','456.jpg', 'ptwampa.jpg', 'taiwan6.jpg']
    @color = params[:color]
    @size = params[:size]
          @width= 4241/8
      @height = 3439/8
    
  end
  
  def contact
    
  end
  
  
  
  
end

workspace/app/helpers/application_helper.rb
module ApplicationHelper
end

workspace/app/helpers/destinations_helper.rb
module DestinationsHelper
end

workspace/app/helpers/welcome_helper.rb
module WelcomeHelper
end

workspace/app/views/destinations/_form.html.erb
<%= form_for(@destination) do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class:'form-control', rows: '5' %>
  </div>
  <div class="field form-group">
    <%= f.label :population %><br>
    <%= f.number_field :population, class: "form-control" %>
  </div>
   <div class="field form-group">
    <%= f.label "Photo" %><br>
    <%= f.file_field :avatar %>
  </div>
 
  <div class="actions">
    <%= f.submit class: 'btn btn-danger' %>
  </div>
<% end %>

workspace/app/views/destinations/edit.html.erb
<h1>Editing Destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

workspace/app/views/destinations/index.html.erb
<p id="notice"><%= notice %></p>

<ul class="nav nav-pills" role="tablist">
 <li><%= link_to "All", destinations_path %></li>
 <li><%= link_to "USA", controller: "destinations", country: "usa" %></li>
 <li><%= link_to "UNITED ARAB EMIRATES", controller: "destinations", country: "united arab emirates" %></li>

</ul>





<h1>Listing Destinations</h1>

<!--<table>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>City</th>-->
<!--      <th>Country</th>-->
<!--      <th>Description</th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
<!--    <% @destinations.each do |destination| %>-->
<!--      <tr>-->
<!--        <td><%= destination.city %></td>-->
<!--        <td><%= destination.country %></td>-->
<!--        <td>Population: <%= destination.population %></td>-->

<!--        <td><%= destination.description %></td>-->
<!--        <td><% if destination.avatar_file_name != nil %>
<--         <%= image_tag destination.avatar.url(:medium), class: "img-responsive" %>-->
<--         <% end %></td>-->
<!--        <td><%= link_to 'Show', destination %></td>-->
<!--        <td><%= link_to 'Edit', edit_destination_path(destination) %></td>-->
<!--        <td><%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--      </tr>-->
<!--    <% end %>-->
<!--  </tbody>-->
<!--</table>-->

<br>


<div class="row">
    <% @destinations.each do |destination| %>
      <div class="col-md-4">
       <div class="panel panel-default">
        <div class="panel-body">
         <h2><%= destination.city %></h2>
         <h3><%= destination.country %></h3>
         <p><%= destination.description %></p>
       
         <div class="btn-group">
          <%= link_to 'Show', destination, class: "btn btn-default" %>
          <%= link_to 'Edit', edit_destination_path(destination), class: "btn btn-default" %>
          <%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
         </div>
        </div>
      </div>
    </div>
  <% end %>
</div>


<%= link_to 'New Destination', new_destination_path, class:'btn btn-danger'%>

workspace/app/views/destinations/new.html.erb
<h1>New Destination</h1>

<%= render 'form' %>


<%= link_to 'Back', destinations_path %>

workspace/app/views/destinations/show.html.erb
<div class="alert alert-success" role="alert">
  <% if notice != nil %>
    <p id="notice" class="alert alert-success" role="alert">
    <%= notice %>
    </p>
  <% end %>
</div>


<h1><%= @destination.city %>, <%= @destination.country %></h1>
<h2>Population <%= @destination.population %></h2>

<p> <%= @destination.description %></p>

<p><% if @destination.avatar_file_name != nil %>
   <%= image_tag @destination.avatar.url(:medium), class: "img-responsive" %>
<% end %>
</p>

<div class="btn-group">
  <%= link_to 'Edit', edit_destination_path(@destination), class: "btn btn-default" %> 
  <%= link_to 'Back', destinations_path, class: "btn btn-default" %>
</div>

workspace/app/views/layouts/_css.html.erb
  
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">
  
    <style>
      /* Only necessary if you are using navbar-fixed-top */
      body {
        padding: 50px;
        background-color: blue;

      }
    </style>
  
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>
  
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

workspace/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Workspace</title>
  
 
  
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">
  
    <style>
      /* Only necessary if you are using navbar-fixed-top */
      body {
        padding: 50px;
        background-color: blue;

      }
    </style>
  
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>
  
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Rails.application.class.parent_name, root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="https://travel2-gandalf23.c9.io/about">About</a></li>
        <li><a href="https://travel2-gandalf23.c9.io/destinations">Destinations</a></li>
        <li><a href="https://travel2-gandalf23.c9.io/contact">Contact Us</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

workspace/app/views/welcome/about.html.erb
<body bgcolor=<%=@color %>>
<h1>About TravelCo</h1>
<p>TravelCo was created at 9:37 am central time on August 25th, 2015, and since that time has become a leader in the travel industry.  We pride outselves on being the best site to go to for all your travel and travel related needs. </p>
<p>Our favorite color is: <%= @color %></p>
<p>Our average shoe size is: <%= @size %></p>
<% if @size.to_i > 12 %>
    <p>"We have HUGE feets!!</p>
<% elsif @size.to_i <6 %>
    <p>"We have teeny tiny feets!"</p>
<% end %>

<%= link_to "Blue", about_path(color: "blue"), class: "btn btn-primary" %>
<p></p>

<% @imagesarray.each do |filename| %>
    <%= image_tag filename ,class: "img-responsive",  width: @width, height: @height%>
<% end %>




<!--<p><a href="https://travel2-gandalf23.c9.io/">Home</a></p>-->

<p><%= link_to "Contact Us", contact_path %></p>

<p><%= link_to "Home", index_path %></p>
</body>

workspace/app/views/welcome/contact.html.erb
<h1>Contact TravelCo!</h1>
<p>For all your travel related needs</p>


<p><%= link_to "About", about_path %></p>

<p><%= link_to "Home", index_path %></p>

workspace/app/views/welcome/index.html.erb
<h1>Welcome to TravelCo's Website</h1>
<p>For all your travel related needs</p>
<p>Our homeland is:  <%=@homeland %></p>
<ul>
<% @countries.each do |name| %>
    <li><%= name %></li>
    
<% end %>
</ul>
    
<%= image_tag "ptwampa.jpg",class: "img-responsive" ,alt: "Preston & Tristan on the Wampa rug", id: "starwars", width: @width, height: @height %>


<%= image_tag "123.jpg" , class: "img-responsive", width: @width, height: @height %>


<%= image_tag "456.jpg",class: "img-responsive", width: @width, height: @height %>


<%= image_tag "taiwan6.jpg", class: "img-responsive", width: @width, height: @height %>



<table class="table table-hover">
  <tr>
    <% @united_states.each do |key,value| %>
	  <th><%= key.titleize %></th>
    <% end %>
  </tr>
  <tr>
    <% @united_states.each do |key,value| %>      
      <% if value.kind_of?(Array) %>
          <td><%= value.join(", ") %></td>
      <% else %>
         <td><%= value %></td>
      <% end %> 
    <% end %>
  </tr>
</table>
    

<!--<p><a href="https://travel2-gandalf23.c9.io/about">About Us</a></p>-->

<p><%= link_to "About", about_path %></p>

<p><%= link_to "Contact Us", contact_path %></p>

<p><%= link_to "Home", index_path %></p>